sudo: required
services:
    - docker

before_install: 
    - docker build -t kiranshetty/docker-react -f "Dockerfile.dev" .

script:
    - docker run -e CI=true kiranshetty/docker-react npm run test
